openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of v5 Restul API
  version: 3.0.0
  title: Bybit Open API v5 explorer - Spot margin trade (normal)
tags:
  - name: normal-margin-trade
    description: Spot margin trade (Classic) endpoints
    x-displayName: Spot Margin Trade (Classic)
x-tagGroups:
  - name: private
    tags:
      - normal-margin-trade
paths:
  /v5/spot-cross-margin-trade/data:
    get:
      tags:
        - normal-margin-trade
      summary: Get VIP Margin Data
      description: Get vip margin data
      operationId: vip-margin
      parameters:
        - name: vipLevel
          in: query
          description: VIP level
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - No VIP
                - VIP-1
                - VIP-2
                - VIP-3
                - VIP-4
                - VIP-5
                - PRO-1
                - PRO-2
                - PRO-3
                - PRO-4
                - PRO-5
        - name: currency
          in: query
          description: Coin name
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/spot-cross-margin-trade/pledge-token:
    get:
      tags:
        - normal-margin-trade
      summary: Get Margin Coin Info
      operationId: margin-data
      parameters:
        - name: coin
          in: query
          description: Coin name
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/spot-cross-margin-trade/borrow-token:
    get:
      tags:
        - normal-margin-trade
      summary: Get Borrowable Coin Info
      operationId: borrowable-data
      parameters:
        - name: coin
          in: query
          description: Coin name
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/spot-cross-margin-trade/loan-info:
    get:
      tags:
        - normal-margin-trade
      summary: Get Interest & Quota
      operationId: interest-quota
      parameters:
        - name: apiKey
          in: header
          description: Please use normal mode account API KEY
          required: true
          schema:
            type: string
        - name: secret
          in: header
          description: Please use normal mode account API SECRET
          required: true
          schema:
            type: string
        - name: coin
          in: query
          description: Coin name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/spot-cross-margin-trade/account:
    get:
      tags:
        - normal-margin-trade
      summary: Get Loan Account Info
      operationId: account-info
      parameters:
        - name: apiKey
          in: header
          description: Please use normal mode account API KEY
          required: true
          schema:
            type: string
        - name: secret
          in: header
          description: Please use normal mode account API SECRET
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/spot-cross-margin-trade/loan:
    post:
      tags:
        - normal-margin-trade
      summary: Borrow
      operationId: borrow
      parameters:
        - name: apiKey
          in: header
          description: Please use normal mode account API KEY
          required: true
          schema:
            type: string
        - name: secret
          in: header
          description: Please use normal mode account API SECRET
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                coin:
                  type: string
                  description: Coin name
                  example: USDT
                qty:
                  type: string
                  description: Amount to borrow
                  example: "1000"
                required:
                  - leverage
                  - qty
  /v5/spot-cross-margin-trade/repay:
    post:
      tags:
        - normal-margin-trade
      summary: Repay
      operationId: Repay
      parameters:
        - name: apiKey
          in: header
          description: Please use normal mode account API KEY
          required: true
          schema:
            type: string
        - name: secret
          in: header
          description: Please use normal mode account API SECRET
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                coin:
                  type: string
                  description: Coin name
                  example: USDT
                qty:
                  type: string
                  description: Amount to repay
                  example: "1000"
                completeRepayment:
                  type: integer
                  description: Whether to pay off all debts. 0：false, 1：true
                  enum:
                    - 0
                    - 1
                  example: 0
                required:
                  - coin
  /v5/spot-cross-margin-trade/orders:
    get:
      tags:
        - normal-margin-trade
      summary: Get Borrow Order Detail
      operationId: borrow-order
      parameters:
        - name: apiKey
          in: header
          description: Please use normal mode account API KEY
          required: true
          schema:
            type: string
        - name: secret
          in: header
          description: Please use normal mode account API SECRET
          required: true
          schema:
            type: string
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: coin
          in: query
          description: Coin name
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Status filter. 0：get all kinds of status, 1：uncleared, 2：cleared
          required: false
          schema:
            type: string
            enum:
              - 0
              - 1
              - 2
        - name: limit
          in: query
          description: Limit for data size per page. 1 - 500. Default：500
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
  /v5/spot-cross-margin-trade/repay-history:
    get:
      tags:
        - normal-margin-trade
      summary: Get Repayment Order Detail
      operationId: repay-order
      parameters:
        - name: apiKey
          in: header
          description: Please use normal mode account API KEY
          required: true
          schema:
            type: string
        - name: secret
          in: header
          description: Please use normal mode account API SECRET
          required: true
          schema:
            type: string
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: coin
          in: query
          description: Coin name
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Limit for data size per page. 1 - 500. Default：500
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
  /v5/spot-cross-margin-trade/switch:
    post:
      tags:
        - normal-margin-trade
      summary: Toggle Margin Trade
      operationId: switch-mode
      parameters:
        - name: apiKey
          in: header
          description: Please use normal mode account API KEY
          required: true
          schema:
            type: string
        - name: secret
          in: header
          description: Please use normal mode account API SECRET
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                switch:
                  type: integer
                  description: 1：on, 0：off
                  example: 0
                required:
                  - switch
