openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of v5 Restul API
  version: 3.0.0
  title: Bybit Open API v5 explorer - User
tags:
  - name: user
    description: User endpoints
    x-displayName: User
x-tagGroups:
  - name: private
    tags:
      - user
paths:
  /v5/user/query-api:
    get:
      tags:
        - user
      summary: Get API Key Information
      description: Get API Key Information
      operationId: apikey-info
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation